---
#create a pod named my-multicontainer-pod, create 2 containers images nginx & redis
apiVersion: v1 
kind: Pod 
metadata: 
  name: my-multicontainer-pod
  labels: 
    author: bharath 
    location: bangalore 
spec: 
  containers:
    - name: my-nginx-container
      image: nginx      
    - name: my-redis-container
      image: redis
...
